name: rutube-qna

services:
  qna-service:
    image: airndlab/rutube-qna:2024.11.21-10-31
    ports:
      - 8080
    volumes:
      - qna_data:/data
    environment:
      - QNA_DB_PATH=/data/metrics.db
      - PIPELINE_BASELINE_SERVICE_URL=http://pipeline-baseline:8080
      - PIPELINE_FAQ_SERVICE_URL=http://pipeline-faq:8080
      - PIPELINE_FAQ_CASES_SERVICE_URL=http://pipeline-faq-cases:8080
      - PIPELINE_RAG_RANKER_SERVICE_URL=http://158.160.85.147:8093

  bot:
    image: airndlab/rutube-qna-bot:2024.11.21-10-30
    depends_on:
      - qna-service
    volumes:
      - ./config:/config
      - bot_data:/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_PATH=/data/settings.db
      - BOT_MESSAGES_FILE_PATH=/config/bot-messages.yml
      - QNA_SERVICE_URL=http://qna-service:8080

volumes:
  bot_data:
  qna_data:
