name: rutube-qna

services:
  pipeline-faq:
    image: airndlab/rutube-qna-pipeline-faq:2024.09.28-12-32
    ports:
      - 8081:8080
    volumes:
      - ./data:/data
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx

  pipeline-faq-cases:
    image: airndlab/rutube-qna-pipeline-faq-cases:2024.09.28-12-38
    ports:
      - 8082:8080
    volumes:
      - ./data:/data
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx
      - CASES_FILE_PATH=/data/cases.xlsx

  pipeline-baseline:
    image: airndlab/rutube-qna-pipeline-baseline:2024.09.27-22-20
    ports:
      - 8088:8080
    volumes:
      - ./data:/data
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx

  qna-service:
    image: airndlab/rutube-qna:2024.09.28-10-32
    ports:
      - 8080:8080
    depends_on:
      - pipeline-faq
      - pipeline-faq-cases
      - pipeline-baseline
    environment:
      - PIPELINE_BASELINE_SERVICE_URL=http://pipeline-baseline:8080
      - PIPELINE_FAQ_SERVICE_URL=http://pipeline-faq:8080
      - PIPELINE_FAQ_CASES_SERVICE_URL=http://pipeline-faq-cases:8080

  bot:
    image: airndlab/rutube-qna-bot:2024.09.28-11-16
    depends_on:
      - qna-service
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - QNA_SERVICE_URL=http://qna-service:8080
