name: rutube-qna

services:
  pipeline-rag-ranker:
    image: airndlab/rutube-qna-pipeline-rag-ranker:2024.09.29-05-28
    ports:
      - 8083:8080
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx
      - CASES_FILE_PATH=/data/cases.xlsx
      - REPLACEMENTS_FILE_PATH=/config/replacements.json

  pipeline-faq:
    image: airndlab/rutube-qna-pipeline-faq:2024.09.28-22-20
    ports:
      - 8081:8080
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx
      - REPLACEMENTS_FILE_PATH=/config/replacements.json

  pipeline-faq-cases:
    image: airndlab/rutube-qna-pipeline-faq-cases:2024.09.28-22-06
    ports:
      - 8082:8080
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx
      - CASES_FILE_PATH=/data/cases.xlsx
      - REPLACEMENTS_FILE_PATH=/config/replacements.json

  pipeline-baseline:
    image: airndlab/rutube-qna-pipeline-baseline:2024.09.27-22-20
    ports:
      - 8088:8080
    volumes:
      - ./data:/data
    environment:
      - KNOWLEDGE_BASE_FILE_PATH=/data/knowledge_base.xlsx

  qna-service:
    image: airndlab/rutube-qna:2024.09.29-05-43
    ports:
      - 8080:8080
    depends_on:
      - pipeline-faq
      - pipeline-faq-cases
      - pipeline-baseline
    volumes:
      - qna_data:/data
    environment:
      - QNA_DB_PATH=/data/metrics.db
      - PIPELINE_BASELINE_SERVICE_URL=http://pipeline-baseline:8080
      - PIPELINE_FAQ_SERVICE_URL=http://pipeline-faq:8080
      - PIPELINE_FAQ_CASES_SERVICE_URL=http://pipeline-faq-cases:8080
      - PIPELINE_RAG_RANKER_SERVICE_URL=http://pipeline-rag-ranker:8080

  bot:
    image: airndlab/rutube-qna-bot:2024.09.29-05-48
    depends_on:
      - qna-service
    volumes:
      - ./config:/config
      - bot_data:/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_PATH=/data/settings.db
      - BOT_MESSAGES_FILE_PATH=/config/bot-messages.yml
      - QNA_SERVICE_URL=http://qna-service:8080

volumes:
  bot_data:
  qna_data:
