start: |
  Привет! Я твой умный помощник Финни.
  Я умею...
  Можно настроить..

  Кнопки демонстрации возможностей "Вопрос 1" "Вопрос 2"

answer: |
  <code>{answer}</code>
  
  <i>Классификатор 1:</i> <code>{class_1}</code>
  <i>Классификатор 2:</i> <code>{class_2}</code>
  
  {other}

like: Спасибо за оценку - рады что Вам понравилось!
dislike: Спасибо за оценку - вы помогаете нам стать лучше!
