start: |
  Привет! Я твой умный помощник Финни.
  Я умею...
  Можно настроить..

  Кнопки демонстрации возможностей "Вопрос 1" "Вопрос 2"
answer: |
  <pre><code>
  {answer}
  </code></pre><i>Уверенность:</i> {assurance}
  <i>Классификатор 1:</i> <code>{class_1}</code>
  <i>Классификатор 2:</i> <code>{class_2}</code>
  
  {other}
answer-confident: "🟢 уверен"
answer-doubtful: "🟡 сомневаюсь, перепроверь"
answer-no: "Извините, я не нашёл подходящий ответ на ваш вопрос. 😩"
pipelines: |
  Текущий пайплайн: {pipeline}
  
  Доступные:
pipeline: "Выбран пайплайн: {pipeline}"
verbose: "На данный момент подробный режим: {status}"
verbose-select: "Подробный режим: {status}"
verbose-enabled: Включен
verbose-disabled: Выключен
like: Спасибо за оценку - рады что Вам понравилось!
dislike: Спасибо за оценку - вы помогаете нам стать лучше!
error: |
  🐬 Ой, что-то пошло не так!
  Пожалуйста, попробуйте еще раз позже.
  Если проблема сохраняется, сообщите администратору.

  {exception}
