FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04 as requirements-stage

RUN apt-get update && apt-get install -y python3.10 python3-pip gcc g++ libffi-dev && apt-get clean

WORKDIR /tmp

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3.10 python3-pip libstdc++6 libffi7 && apt-get clean

WORKDIR /code

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN python3 -m nltk.downloader punkt

COPY ./app /code/app

EXPOSE 8080

LABEL org.opencontainers.image.vendor="AI RnD Lab"

CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8080"]
