name: Docker image

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project path'
        required: true
        type: choice
        options:
          - bot
          - qna
          - pipelines/baseline
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{ github.repository }}:${{ steps.date_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate date tag
        id: date_tag
        run: |
          echo "tag=$(date +'%Y.%m.%d-%H-%M')" >> $GITHUB_ENV

      - name: Create Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.date_tag.outputs.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/${{ inputs.project }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
